### ISSUE TITLE
Move to openmm org and rename to openmm-tensorflow?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm-nn#13]
Would it make sense to move this repo and the PyTorch-based repo to the http://github.com/openmm org? 

We would probably want to name it something like `openmm-tensorflow` to make it clear that this supports the TensorFlow library and distinguish it from the `openmm-torch` plugin.

**Comment by jchodera** [comment]
@peastman : What do you think about renaming this to `openmm-tensorflow` to make it clear that this plugin provides support for TensorFlow (in analogy to `openmm-torch`)?

**Comment by peastman** [comment]
Seems plausible.  I assume you're talking about renaming not just the repository, but also the Python module and the force class?

**Comment by jchodera** [comment]
Great idea!

**Comment by jchodera** [comment]
@peastman: OK if I rename this to `openmm-tensorflow`?

**Comment by peastman** [comment]
Ok.

**Comment by jchodera** [comment]
Done.
